import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="es">
         <Providers>
            <body className={inter.className}>
               <Toaster
                  toastOptions={{
                     duration: 4000,
                     style: {
                        background: "#D12222",
                        color: "#fff",
                     },
                  }}
               />
               {children}
            </body>
         </Providers>
      </html>
   );
}
